FORMAT: 1A
HOST: http://polls.apiblueprint.org/

# Micro App1 API Test Case

Micro App1 is a simple API which will allow us to test the use of apiary in api design. 
It will allow software teams to speed up the process by allowing them to design, test, and document 
the api at the same time rather than doing it individually one process at a time.

**Naming Convention**  
*Base app:* Sapho  
*Micro app name:* ImageNow Approver

## Invoice [/invoiceID]
An object of invoices which stores their identification numbers as 
the property **invoiceID**.

### List Invoice Properties [GET]

+ Response 200 (application/json)

        [
            "invoiceID" : "00001",
            "import_time": "2015-08-05T08:40:51.620Z",
            "approver_name": "Roy Gallagher",
            "approval_status": 
            [
                {
                    "approve": "Approve"
                }, 
                {
                    "reject": "Reject"
                    "reason": "Reasoning"
                }
            ]
                
        ]